---
- name: Install MicroK8s
  become: true
  snap:
    name: microk8s
    classic: yes

- name: Add user to microk8s group
  user:
    name: "{{ ansible_user }}"
    groups: microk8s
    append: yes

