---
- name: Install MicroK8s
  snap:
    name: microk8s
    classic: yes

- name: Add user to microk8s group
  user:
    name: "{{ ansible_user }}"
    group: microk8s
    append: yes

- name: Wait for MicroK8s to be ready
  command: microk8s.status --wait-ready
  register: mk8sstatusout
  failed_when:
    - "'This MicroK8s deployment is acting as a node in a cluster.' not in mk8sstatusout.stdout_lines"
    - mk8sstatusout.rc > 0
  changed_when: false