---
- name: Assert usecase
  assert:
    that:
      - usecase in exist_usecases
    fail_msg: "Incorrect value of usecase: {{ usecase }}. Allowed values: {{ exist_usecases | join(', ') }}."
    success_msg: "usecase is correct: {{ usecase }}."
- name: Apt install
  when: usecase == "install"
  include_tasks: install_microk8s.yaml
- name: Setup ufw
  when: usecase == "install" and ufw.enabled
  include_tasks: setup_ufw.yaml
- name:  Setup route-service
  when: usecase == "install" and route_service.enabled
  include_tasks: setup_route_service.yaml
- name:  Assert MicroK8S is running
  include_tasks: usecase == "install" and assert_is_running.yaml
- name: Setup plugins
  when: usecase == "install" and microk8s_plugins.enabled
  include_tasks: setup_plugins.yaml
- name: get to kubeconfig
  when: ( usecase == "install" or usecase == "get_kubeconfig" ) and get_kubeconfig.enabled
  include_tasks: get_kubeconfig.yaml