- name: Copy Template file
  template:
    src: route-service.j2
    dest: /etc/systemd/system/add-route.service
    owner: root
    group: root
    mode: '0644'
  notify: systemd updated

- name: Restart systemd
  systemd:
    daemon_reload: true

- name: Enable awg-quick service
  systemd:
    name: add-route.service
    enabled: true
    state: started

- name: Assert awg-quick service is running
  systemd:
    name: add-route.service
    state: started
  register: service_status
  failed_when: service_status.status["ActiveState"] != "active"
  changed_when: false
  retries: 5
  delay: 10